site:
  title: "Kayo Ennrique - Timeline"
  description: "Bem vindo a minha timeline pessoal"
personal:
  name: "Kayo Ennrique"
  avatar: "https://github.com/kayoennrique.png"
  socialNetworks:
    youtube: "https://www.youtube.com/"
    github: "https://www.github.com/kayoennrique"
    twitter: "https://www.twitter.com/kayoennrique"
    linkedin: "https://www.linkedin.com/in/kayoennrique"
